/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ManagerFelipeIndexRouteImport } from './routes/manager-felipe/index'
import { Route as ManagerFelipeLoginRouteImport } from './routes/manager-felipe/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerFelipeIndexRoute = ManagerFelipeIndexRouteImport.update({
  id: '/manager-felipe/',
  path: '/manager-felipe/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerFelipeLoginRoute = ManagerFelipeLoginRouteImport.update({
  id: '/manager-felipe/login',
  path: '/manager-felipe/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/obrigado': typeof ObrigadoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/manager-felipe/login': typeof ManagerFelipeLoginRoute
  '/manager-felipe/': typeof ManagerFelipeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/obrigado': typeof ObrigadoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/manager-felipe/login': typeof ManagerFelipeLoginRoute
  '/manager-felipe': typeof ManagerFelipeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/obrigado': typeof ObrigadoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/manager-felipe/login': typeof ManagerFelipeLoginRoute
  '/manager-felipe/': typeof ManagerFelipeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/obrigado'
    | '/sitemap.xml'
    | '/manager-felipe/login'
    | '/manager-felipe/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/obrigado'
    | '/sitemap.xml'
    | '/manager-felipe/login'
    | '/manager-felipe'
  id:
    | '__root__'
    | '/'
    | '/obrigado'
    | '/sitemap.xml'
    | '/manager-felipe/login'
    | '/manager-felipe/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ObrigadoRoute: typeof ObrigadoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ManagerFelipeLoginRoute: typeof ManagerFelipeLoginRoute
  ManagerFelipeIndexRoute: typeof ManagerFelipeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager-felipe/': {
      id: '/manager-felipe/'
      path: '/manager-felipe'
      fullPath: '/manager-felipe/'
      preLoaderRoute: typeof ManagerFelipeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager-felipe/login': {
      id: '/manager-felipe/login'
      path: '/manager-felipe/login'
      fullPath: '/manager-felipe/login'
      preLoaderRoute: typeof ManagerFelipeLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ObrigadoRoute: ObrigadoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ManagerFelipeLoginRoute: ManagerFelipeLoginRoute,
  ManagerFelipeIndexRoute: ManagerFelipeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
